site_name: David O'Connor for NC Legislature
site_url: https://www.davidoconnornc.com
use_directory_urls: false

docs_dir: md_pages

theme:
  name: material
  icon:
    repo: material/home

#  features:
#    - navigation.tabs

nav:
  - Back to home page: "/"
  - Introduction: index.md
  - Election reform: election_reform.md
  - Housing: housing.md
  - Community Feedback: community_feedback.md
  - Infrastructure: infrastructure_repair.md
  # - Bills I support: bills
  # - Drafted Legislation

extra:
  generator: false
  homepage: https://www.davidoconnornc.com
